
build: off

clone_folder: c:\gopath\src\github.com\notomo\wsxhub

environment:
    GOPATH: c:\gopath
    GO111MODULE: on

stack: go 1.12

before_test:
    - set PATH=%GOPATH%\bin;%PATH%

test_script:
    - echo %PATH%
    - go build -o dist/wsxhub.exe
    - go test -v github.com/notomo/wsxhub/...
